-- ----------------------------------------------------------------
-- 🛑 DO NOT EDIT THIS FILE!
-- Regenerated by: edgespark pull schema --db
--
-- To modify your database schema (multiple statements in one command):
--   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
--     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
--     CREATE INDEX idx_posts_created ON posts(created_at)"
--
-- To query your database:
--   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
-- ----------------------------------------------------------------

-- TABLES

CREATE TABLE assessments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  assessment_type TEXT NOT NULL,
  overall_score INTEGER,
  wealth_score INTEGER,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE consultations (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  scheduled_at INTEGER,
  duration_minutes INTEGER DEFAULT 60,
  status TEXT DEFAULT 'scheduled',
  notes TEXT,
  advisor_name TEXT,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now'))
);

CREATE TABLE `es_system__auth_user` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT false NOT NULL,
	`image` text,
	`created_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`updated_at` integer DEFAULT (cast(unixepoch('subsecond') * 1000 as integer)) NOT NULL,
	`is_anonymous` integer DEFAULT false,
	`__internal_a` text,
	`banned` integer DEFAULT false,
	`ban_reason` text,
	`ban_expires` integer,
	`last_login_at` integer
);

CREATE TABLE orders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  user_id TEXT NOT NULL,
  price_id INTEGER REFERENCES payment_prices(id),
  amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'usd',
  status TEXT DEFAULT 'pending',
  type TEXT DEFAULT 'one_time',
  provider TEXT,
  provider_session_id TEXT,
  provider_payment_id TEXT,
  provider_invoice_id TEXT,
  metadata TEXT,
  paid_at INTEGER,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE payment_accounts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  user_id TEXT NOT NULL,
  provider TEXT NOT NULL,
  provider_customer_id TEXT NOT NULL,
  email TEXT,
  metadata TEXT,
  created_at INTEGER DEFAULT (unixepoch()),
  UNIQUE(environment, user_id, provider)
);

CREATE TABLE payment_prices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  name TEXT NOT NULL,
  description TEXT,
  amount INTEGER NOT NULL,
  currency TEXT DEFAULT 'usd',
  type TEXT DEFAULT 'one_time',
  interval TEXT,
  provider TEXT NOT NULL,
  provider_product_id TEXT,
  provider_price_id TEXT,
  active INTEGER DEFAULT 1,
  metadata TEXT,
  created_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE pillar_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  assessment_id INTEGER NOT NULL,
  pillar_name TEXT NOT NULL,
  pillar_key TEXT NOT NULL,
  raw_score INTEGER,
  weight REAL DEFAULT 1.0,
  weighted_score INTEGER,
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  FOREIGN KEY (assessment_id) REFERENCES assessments(id)
);

CREATE TABLE subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  environment TEXT NOT NULL DEFAULT 'staging',
  user_id TEXT NOT NULL,
  price_id INTEGER REFERENCES payment_prices(id),
  status TEXT DEFAULT 'active',
  provider TEXT NOT NULL,
  provider_subscription_id TEXT,
  current_period_start INTEGER,
  current_period_end INTEGER,
  cancel_at_period_end INTEGER DEFAULT 0,
  canceled_at INTEGER,
  metadata TEXT,
  created_at INTEGER DEFAULT (unixepoch()),
  updated_at INTEGER DEFAULT (unixepoch())
);

CREATE TABLE user_profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL UNIQUE,
  name TEXT,
  email TEXT,
  is_premium INTEGER DEFAULT 0,
  subscription_status TEXT DEFAULT 'free',
  created_at INTEGER DEFAULT (strftime('%s', 'now')),
  updated_at INTEGER DEFAULT (strftime('%s', 'now'))
);

-- INDEXS

CREATE INDEX assessments_type_idx ON assessments(assessment_type);

CREATE INDEX assessments_user_id_idx ON assessments(user_id);

CREATE INDEX consultations_status_idx ON consultations(status);

CREATE INDEX consultations_user_id_idx ON consultations(user_id);

CREATE UNIQUE INDEX `es_system__auth_user_email_unique` ON `es_system__auth_user` (`email`);

CREATE INDEX orders_env_session_idx ON orders(environment, provider, provider_session_id);

CREATE INDEX orders_env_status_idx ON orders(environment, status);

CREATE INDEX orders_env_user_idx ON orders(environment, user_id);

CREATE INDEX payment_accounts_env_idx ON payment_accounts(environment, provider, provider_customer_id);

CREATE INDEX payment_prices_env_idx ON payment_prices(environment, provider, provider_price_id);

CREATE INDEX pillar_scores_assessment_idx ON pillar_scores(assessment_id);

CREATE INDEX subscriptions_env_provider_idx ON subscriptions(environment, provider, provider_subscription_id);

CREATE INDEX subscriptions_env_user_idx ON subscriptions(environment, user_id);

CREATE INDEX user_profiles_user_id_idx ON user_profiles(user_id);
