// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { relations } from "drizzle-orm/relations";
import { assessments, pillarScores, paymentPrices, orders, subscriptions } from "./db_schema";

export const pillarScoresRelations = relations(pillarScores, ({one}) => ({
	assessment: one(assessments, {
		fields: [pillarScores.assessmentId],
		references: [assessments.id]
	}),
}));

export const assessmentsRelations = relations(assessments, ({many}) => ({
	pillarScores: many(pillarScores),
}));

export const ordersRelations = relations(orders, ({one}) => ({
	paymentPrice: one(paymentPrices, {
		fields: [orders.priceId],
		references: [paymentPrices.id]
	}),
}));

export const paymentPricesRelations = relations(paymentPrices, ({many}) => ({
	orders: many(orders),
	subscriptions: many(subscriptions),
}));

export const subscriptionsRelations = relations(subscriptions, ({one}) => ({
	paymentPrice: one(paymentPrices, {
		fields: [subscriptions.priceId],
		references: [paymentPrices.id]
	}),
}));