// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index, foreignKey, real } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const assessments = sqliteTable("assessments", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	assessmentType: text("assessment_type").notNull(),
	overallScore: integer("overall_score"),
	wealthScore: integer("wealth_score"),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("assessments_type_idx").on(table.assessmentType),
	index("assessments_user_id_idx").on(table.userId),
]);

export const pillarScores = sqliteTable("pillar_scores", {
	id: integer().primaryKey({ autoIncrement: true }),
	assessmentId: integer("assessment_id").notNull().references(() => assessments.id),
	pillarName: text("pillar_name").notNull(),
	pillarKey: text("pillar_key").notNull(),
	rawScore: integer("raw_score"),
	weight: real().default(1),
	weightedScore: integer("weighted_score"),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("pillar_scores_assessment_idx").on(table.assessmentId),
]);

export const consultations = sqliteTable("consultations", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	scheduledAt: integer("scheduled_at"),
	durationMinutes: integer("duration_minutes").default(60),
	status: text().default("scheduled"),
	notes: text(),
	advisorName: text("advisor_name"),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("consultations_status_idx").on(table.status),
	index("consultations_user_id_idx").on(table.userId),
]);

export const userProfiles = sqliteTable("user_profiles", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	name: text(),
	email: text(),
	isPremium: integer("is_premium").default(0),
	subscriptionStatus: text("subscription_status").default("free"),
	createdAt: integer("created_at").default(sql`(strftime('%s', 'now'))`),
	updatedAt: integer("updated_at").default(sql`(strftime('%s', 'now'))`),
},
(table) => [
	index("user_profiles_user_id_idx").on(table.userId),
]);

export const paymentPrices = sqliteTable("payment_prices", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	name: text().notNull(),
	description: text(),
	amount: integer().notNull(),
	currency: text().default("usd"),
	type: text().default("one_time"),
	interval: text(),
	provider: text().notNull(),
	providerProductId: text("provider_product_id"),
	providerPriceId: text("provider_price_id"),
	active: integer().default(1),
	metadata: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("payment_prices_env_idx").on(table.environment, table.provider, table.providerPriceId),
]);

export const paymentAccounts = sqliteTable("payment_accounts", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	userId: text("user_id").notNull(),
	provider: text().notNull(),
	providerCustomerId: text("provider_customer_id").notNull(),
	email: text(),
	metadata: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("payment_accounts_env_idx").on(table.environment, table.provider, table.providerCustomerId),
]);

export const orders = sqliteTable("orders", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	userId: text("user_id").notNull(),
	priceId: integer("price_id").references(() => paymentPrices.id),
	amount: integer().notNull(),
	currency: text().default("usd"),
	status: text().default("pending"),
	type: text().default("one_time"),
	provider: text(),
	providerSessionId: text("provider_session_id"),
	providerPaymentId: text("provider_payment_id"),
	providerInvoiceId: text("provider_invoice_id"),
	metadata: text(),
	paidAt: integer("paid_at"),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
},
(table) => [
	index("orders_env_session_idx").on(table.environment, table.provider, table.providerSessionId),
	index("orders_env_status_idx").on(table.environment, table.status),
	index("orders_env_user_idx").on(table.environment, table.userId),
]);

export const subscriptions = sqliteTable("subscriptions", {
	id: integer().primaryKey({ autoIncrement: true }),
	environment: text().default("staging").notNull(),
	userId: text("user_id").notNull(),
	priceId: integer("price_id").references(() => paymentPrices.id),
	status: text().default("active"),
	provider: text().notNull(),
	providerSubscriptionId: text("provider_subscription_id"),
	currentPeriodStart: integer("current_period_start"),
	currentPeriodEnd: integer("current_period_end"),
	cancelAtPeriodEnd: integer("cancel_at_period_end").default(0),
	canceledAt: integer("canceled_at"),
	metadata: text(),
	createdAt: integer("created_at").default(sql`(unixepoch())`),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`),
},
(table) => [
	index("subscriptions_env_provider_idx").on(table.environment, table.provider, table.providerSubscriptionId),
	index("subscriptions_env_user_idx").on(table.environment, table.userId),
]);

